### ISSUE TITLE
Need to reload mona and x64dbgpylib when new exe is opened

### ISSUE THREAD

**Issue by wangray** [x64dbg/x64dbgpylib#8]
Right now, loading a new file does not clear the global variables in x64dbgpylib, so mona will return old values. I have to manually reload with `reload(mona); reload(mona.dbglib)`, etc...

@mrexodia Maybe leave it to x64dbgpy to blow away all state and modules when a new exe is loaded?

**Comment by mrexodia** [comment]
Currently x64dbgpy keeps the state of loaded files to support using the python interpreter directly from the command bar. Perhaps a solution could be to add a script to the `autorun` folder that reloads everything? See [here](https://github.com/x64dbg/x64dbgpy/blob/v25/py.cpp#L354).

**Comment by wangray** [comment]
The autorun solution seems to work ok. I've added the script to the PR.
